// INPUT
export const SELECT_CELL = 'SELECT_CELL';
export const UNSELECT_CELL = 'UNSELECT_CELL';
export const NUMBER_INPUT = 'NUMBER_INPUT';
export const MANAGE_INPUTS = 'MANAGE_INPUTS';
export const ATTEPMT_SOLVE = 'ATTEMPT_SOLVE';
export const COUNT_NUMBER_INPUTS = 'COUNT_NUMBER_INPUTS';

// GRID
export const CHANGE_CELL_NUM = 'CHANGE_CELL_NUM';
export const RESET_CELL = 'RESET_CELL';
export const SET_COULD_BE = 'SET_COULD_BE';
export const COULD_BE_AFTER_CLEAR = 'COULD_BE_AFTER_CLEAR';
export const CHECK_COULD_BE_SWEEP = 'CHECK_COULD_BE_SWEEP';
